### ISSUE TITLE
Commands fail to execute if argument is a path containing space

### ISSUE THREAD

**Issue by maciek-codes** [Microsoft/run-in-terminal#1]
Under Windows, if a command takes e.g. path as an argument and the path contains a space, it fails to execute.

E.g. `dir C:\Users\Foo Bar` would fail to execute therefore it needs escaping.
The correct way of passing such a path is to escape it with quotes:
`dir "C:\Users\Foo Bar"`.

Because Windows allow spaces in folders, it causes a lot of issues, esp. in Visual Studio Code.

**Comment by jtsom** [comment]
Please accept this fix!!! Causes VS Code to not run DNX commands!!!
